
services:
  - type: web
    name: alignerservice-rag
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port 10000
    autoDeploy: true
    buildFilter:
      paths:
        included:
          - app.py
          - requirements.txt
          - *.json
