services:
  - type: web
    name: rag-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        fromSecret: OPENAI_API_KEY
      - key: DROPBOX_CLIENT_ID
      - key: DROPBOX_CLIENT_SECRET
      - key: DROPBOX_REFRESH_TOKEN
      - key: DROPBOX_DB_PATH
      - key: ZOHO_CLIENT_ID
      - key: ZOHO_CLIENT_SECRET
      - key: ZOHO_REFRESH_TOKEN
      - key: LOCAL_DB_PATH
        value: /tmp/knowledge.sqlite
      # Din eksisterende embedding-nøgle. Koden bruger OPENAI_EMBED_MODEL nedenfor.
      - key: OPENAI_EMBEDDING_MODEL
        value: text-embedding-ada-002
      - key: OPENAI_CHAT_MODEL
        value: gpt-4
      - key: OPENAI_TEMPERATURE
        value: "0.2"

      # --- Nye nøgler til forbedret retrieval/rerank (bruges af din opdaterede kode) ---
      - key: OPENAI_EMBED_MODEL
        value: text-embedding-3-large
      - key: RETR_K
        value: "40"
      - key: RERANK_TOPK
        value: "12"
      - key: MMR_LAMBDA
        value: "0.4"
