services:
  - type: web
    name: rag-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: OPENAI_API_KEY
        fromSecret: OPENAI_API_KEY
      - key: DROPBOX_CLIENT_ID
      - key: DROPBOX_CLIENT_SECRET
      - key: DROPBOX_REFRESH_TOKEN
      - key: DROPBOX_DB_PATH
      - key: ZOHO_CLIENT_ID
      - key: ZOHO_CLIENT_SECRET
      - key: ZOHO_REFRESH_TOKEN
      - key: LOCAL_DB_PATH
        value: /tmp/knowledge.sqlite
      - key: OPENAI_EMBEDDING_MODEL
        value: text-embedding-ada-002
      - key: OPENAI_CHAT_MODEL
        value: gpt-4
      - key: OPENAI_TEMPERATURE
        value: "0.2"
