services:
  - type: web
    name: rag-chatbot-base
    env: python
    plan: starter
    buildCommand: pip install -r requirements.txt
startCommand: uvicorn app.__init__:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: DROPBOX_TOKEN
        fromEnvVar: DROPBOX_TOKEN
      - key: ZOHO_CLIENT_ID
        fromEnvVar: ZOHO_CLIENT_ID
      - key: ZOHO_CLIENT_SECRET
        fromEnvVar: ZOHO_CLIENT_SECRET
      - key: ZOHO_REFRESH_TOKEN
        fromEnvVar: ZOHO_REFRESH_TOKEN
      - key: DROPBOX_DB_PATH
        value: /knowledge.sqlite
      - key: LOCAL_DB_PATH
        value: /tmp/knowledge.sqlite
      - key: DATABASE_PATH
        value: /tmp/knowledge.sqlite
