name: Build FAISS Index

on:
  push:
    branches: [ main ]    # eller dit primære branch-navn

jobs:
  build-index:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build FAISS index
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          python scripts/build_index.py

      - name: Upload index and id-mapping
        uses: actions/upload-artifact@v4
        with:
          name: faiss-index
          path: |
            faiss.index
            id_mapping.csv
